app:
  name: rg-portal
mysql:
  install: true
  host: localhost
  username: rails
  password: password
  database: rg_portal
nginx:
  host: portal.gw.sfc.wide.ad.jp
  name: rg-portal
ndenv:
  global:
    5.8.0
  versions:
    - 5.8.0
  packages:
    - bower
rbenv:
  global:
    2.2.1
  versions:
    - 2.2.1
  gems:
    - bundler
letsencrypt:
  domain: portal.gw.sfc.wide.ad.jp
  email: miyukki@sfc.wide.ad.jp
  document_root: /var/www/rg-portal/current/public
solr:
  version: 5.4.1
  core: production
